# Generated by Django 4.2.5 on 2023-10-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='point_title',
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
