# Generated by Django 4.2.5 on 2023-10-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_place_place_id_remove_place_point_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(unique=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('file', 'place')},
        ),
    ]
